`define INST_TABLE_WD   52
`define ERET            0
`define LB              1
`define LW              2
`define LBU             3
`define LH              4
`define LHU             5
`define SH              6
`define SW              7
`define SB              8
`define DIV             9
`define DIVU            10
`define MULT            11
`define MULTU           12
`define MFHI            13
`define MFLO            14
`define MFC0            15
`define MUL             16
`define MADD            17
`define MADDU           18
`define MSUB            19
`define MSUBU           20
`define TLBP            21
`define TLBR            22
`define TLBWI           23
`define TGE             24
`define TGEI            25
`define TGEU            26
`define TGEIU           27
`define TLT             28
`define TLTI            29
`define TLTU            30
`define TLTIU           31  
`define TEQ             32
`define TEQI            33
`define TNE             34
`define TNEI            35
`define CLO             36
`define CLZ             37
`define MOVN            38
`define MOVZ            39
`define LWL             40
`define LWR             41
`define SWL             42
`define SWR             43
`define LL              44
`define SC              45
`define CACHE           46
`define WAIT            47
`define TLBWR           48
`define JAL             49
`define JALR            50
`define RET             51
`define EX_INFO         18

`define PRE_IF_EX_INFO 5
`define IF_EX_INFO     5
`define ID_EX_INFO     18
`define EXE_EX_INFO    18
`define MEM0_EX_INFO   18
`define MEM_EX_INFO    18
`define WR_EX_INFO     18